export { default as NavBar } from './Navbar'
export { default as Motion } from './Motion'
export { default as Main } from './Main'
export { default as About } from './About'
export { default as Portfolio } from './Portfolio'
export { default as Contact } from './Contact'